# -*- coding: utf-8 -*-
"""R2_amexWK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvULIscTEOkkx8R-eNrUeM-opsld4DNU
"""

# Loading batsman working excel and checking for top wicketkeeper obatined while calculating for top batsmen
df_wicketkeeper = pd.read_excel('round2_working_Batsman.xlsx')
keeper_count = (df_wicketkeeper['is_batsman_keeper']==1).groupby(df_wicketkeeper['batsman_id']).sum()
keeper_count_df = keeper_count.reset_index(name='keeper_count')
keeper_count_df.sort_values(by='keeper_count', ascending = False)
keeper_count_df[keeper_count_df['batsman_id'].isin([2162782,313809,3125562])]